### ISSUE TITLE
Add date ranges to pricing

### ISSUE THREAD

**Issue by FamousTate** [FamousTate/Whirlwind#21]
this would allow for setting future pricing for sales and promotions.

**Comment by WhirlWindSoftware** [comment]
this is complete in beta mode. Need import information.

**Comment by FamousTate** [comment]
I think you got the information you were looking for.  If this is complete on your side, can you close the issue?

**Comment by FamousTate** [comment]
Last I heard, this was working in whirlwind but not implemented at Tate for unknown reasons.  Closing issue because job is done.
