### ISSUE TITLE
Force warranty attachment at the time of sale

### ISSUE THREAD

**Issue by FamousTate** [FamousTate/Whirlwind#35]
Force warranty attachment at the time of sale

**Comment by WhirlWindSoftware** [comment]
This is completed. You need to go to the employee's right screen to activate this. We put it for each employee so office people can look at a customer order  without having to attach, but sales people cannot exit the Order or Back Order without warranties attached.
It is marked as "Cannot Exit an Order with Warranties not Attached"
1 1/2 hours

**Comment by FamousTate** [comment]
@WhirlWindSoftware included this feature.  It introduced new bugs that were covered in other open tickets

**Comment by FamousTate** [comment]
issue created from this feature: https://github.com/FamousTate/Whirlwind/issues/35

**Comment by FamousTate** [comment]
issue created from this feature: https://github.com/FamousTate/Whirlwind/issues/40
