### ISSUE TITLE
Issue printing price tags with as-is pricing

### ISSUE THREAD

**Issue by FamousTate** [FamousTate/Whirlwind#38]
from Jason: 

> When we add a model to print a depot tag from the As-Is field, we get an error message. All other price fields work.

here's a copy of the resulting error:
![image](https://cloud.githubusercontent.com/assets/11324842/22155206/43578100-def4-11e6-8949-a14b3e4c52e8.png)

**Comment by WhirlWindSoftware** [comment]
Resolved

**Comment by WhirlWindSoftware** [comment]
Done Checked with Jason a while ago. Check again in Apr 2017 to verify
